services:
    db:
        image: mysql:8.0
        container_name: bai8-mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3310:3306"
        volumes:
            - db_data:/var/lib/mysql

    app:
        build: .
        container_name: bai8-node-app
        depends_on:
            - db
        ports:
            - "3008:3000"

volumes:
    db_data:
