services:
    node-exporter:
        image: prom/node-exporter:latest
        container_name: bai12-node-exporter
        ports:
            - "9100:9100"

    prometheus:
        image: prom/prometheus:latest
        container_name: bai12-prometheus
        depends_on:
            - node-exporter
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

    grafana:
        image: grafana/grafana:latest
        container_name: bai12-grafana
        depends_on:
            - prometheus
        ports:
            - "3001:3000"
        volumes:
            - grafana_data:/var/lib/grafana

volumes:
    grafana_data:
